name: gitlab-push

on:
  push:
    branches: [ master ]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Push To Gitlab
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "GitHub Actions"
        git config user.email github-actions@localhost
        git remote set-url origin "https://oauth2:${token}@git.callahtech.com/jcallahan/qr-code-site.git"
        git push origin master --force